### ISSUE TITLE
TTSVoiceWizard is looking for assets not in its own directory

### ISSUE THREAD

**Issue by Naveandice** [VRCWizard/TTS-Voice-Wizard#49]
Greetings! Just upgraded to version 1.5.1.7 and tried to use Text-to-Speech in System Speech mode, the program crashes after the second use. Crash dumps didn't appear in the program directory. Using Event Viewer, it turned out that TTSVoiceWizard crashes with an error `System.IO.DirectoryNotFoundException`, trying to find assets not in its own directory, but in the directory of the voice used. Here are the general details straight from the Event Viewer:

<details><summary>Event 1026, .NET Runtime</summary>

```
Application: TTSVoiceWizard.exe
CoreCLR Version: 6.0.1823.26907
.NET Version: 6.0.18
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Speech2Go Voice Package\x64\Assets\sounds\TTSButton.wav'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenRead(String path)
   at NAudio.Wave.WaveFileReader..ctor(String waveFile)
   at OSCVRCWiz.Resources.Audio.AudioDevices.PlaySoundAsync(String soundName) in {Filtered}\OSCVRCWiz\Resources\Audio\AudioDevices.cs:line 483
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```
_Excluded some part of the path for privacy reasons._

</details>

**Comment by VRCWizard** [comment]
For now you could try running TTS Voice Wizard as administrator, or moving it's entire folder to a new location.

or if those fail you could just try turning off button sounds 
![image](https://github.com/VRCWizard/TTS-Voice-Wizard/assets/101527472/6af8a7f0-3fea-449a-8ff2-e38366e20432)


Other than that, next update I'll make all applicable locations use absolute paths rather than relative paths (that don't seem to always return the correct path). Also, exception handling for the button sounds.

**Comment by Naveandice** [comment]
Running as administrator and moving (copying) to a new location causes the same error, so I just turned off the button sounds. Thanks!

**Comment by Naveandice** [comment]
Updated to 1.5.4, now everything works as intended. Thank you very much once again!
